### ISSUE TITLE
If app launched due to an iOS 7 Background Fetch MOC never set

### ISSUE THREAD

**Issue by kdbdallas** [lhunath/UbiquityStoreManager#20]
If you enable background updating in your app and then have your app launch due to a background fetch (either by an actual fetch time, or by setting the value in the scheme), the MOC is not getting set.

didLoadStoreForCoordinator, is never getting called.

The logs from launching this way are as follows:

UbiquityStoreManager: Loading store...
UbiquityStoreManager: Will load cloud store.
UbiquityStoreManager: Clearing stores...
UbiquityStoreManager: Will clear stores.  Notifying application to reset its UI.

Thats it.
It never goes anywhere else.
If you launch normally then it works as expected.

**Comment by lhunath** [comment]
What do you see it doing in the persistence queue when you pause the app from the debugger?

**Comment by kdbdallas** [comment]
Even after letting it sit and 'run' for awhile when I pause I always see the following

![screen shot 2013-11-14 at 3 41 26 pm](https://f.cloud.github.com/assets/59203/1545997/01db700c-4d7e-11e3-9811-5846ca3383b6.png)

**Comment by lhunath** [comment]
Try the latest HEAD.

**Comment by kdbdallas** [comment]
It gets further along but now it gets stuck at

![screen shot 2013-11-14 at 7 16 02 pm](https://f.cloud.github.com/assets/59203/1547313/ff932290-4d9b-11e3-86af-0ddfe4e712f4.png)

**Comment by lhunath** [comment]
Do you think you could build me a small sample app that loads a USM store in the background or modify the USM example to reproduce this?

**Comment by kdbdallas** [comment]
Yea. Its easy really. All you have to do is select Background Fetch under Background Modes in the Capabilities section of the project.

Then in your scheme just set it to launch due to background fetch

I can put one together if you want, but its 10000x easier if you have an existing project where you can just set these 2 things.

![screen shot 2013-12-01 at 10 37 39 am](https://f.cloud.github.com/assets/59203/1650793/7589b9da-5aaf-11e3-8b49-e4c34d7cdbd6.png)

**Comment by lhunath** [comment]
I'm not experiencing any issues loading USM as a result of a background fetch.  I'm pretty sure I'm starting the app in the background as the UI isn't appearing and the `-(void)application:(UIApplication *)application performFetchWithCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler` is invoked.  The cloud store loads fine.

**Comment by kdbdallas** [comment]
I think your update might have fixed it. I am looking into it

**Comment by kdbdallas** [comment]
So I am getting into performFetch... but if I try and do anything my MOC is nil

**Comment by kdbdallas** [comment]
- (void)ubiquityStoreManager:(UbiquityStoreManager *)manager didLoadStoreForCoordinator:(NSPersistentStoreCoordinator *)coordinator isCloud:(BOOL)isCloudStore

is never getting called, so MOC never gets set.
I think its because performFetch ends too soon.
Perhaps this has to do with the fall back store issue

**Comment by lhunath** [comment]
Can you share your USM delegate methods and init call?

**Comment by lhunath** [comment]
Can you try moving `self.ubiquityStoreManager.cloudEnabled = YES;` into `ubiquityStoreManager:willLoadStoreIsCloud:`?

**Comment by kdbdallas** [comment]
Still nope.
It goes into willLoadStoreIsCloud it tries to access self.managedObjectContext but it is nil
Never gets to didLoadStore just then hits the fetch method which kills it off since there is no MOC to do any work with

**Comment by lhunath** [comment]
Does this occur only on the device or also in the simulator?

**Comment by kdbdallas** [comment]
On the simulator it hits the performFetchWithCompletionHandler then does hit didLoadStore, but the spot where you are supposed to do data has long come and gone.

It looks like the simulator doesn't really handle UIBackgroundFetchResult completionHandler (which tells the system the app is done)

**Comment by lhunath** [comment]
It is expected that the store is not yet loaded by the time `performFetch` is called.  The store is loaded asynchronously and becomes available when it does.  `performFetch` is invoked as soon as the application delegate has started.  You'll need to wait for your second background fetch event to start using the store (so you should probably check if the MOC is available and if not do nothing).

Alternatively, you can try to block `performFetch` until the store comes online, but I don't recommend it as this method is supposed to run as fast as possible.

**Comment by lhunath** [comment]
Even on the device, my store becomes available (albeit after the first `performFetch`).  I cannot reproduce this hang you're seeing :-/

**Comment by lhunath** [comment]
Actually, I can reproduce it.

If I uninstall the app from the device, then launch it, the app initially blocks on the same point you did.  Presumably because Apple cannot construct the ubiquity container in the background.  But as soon as the app becomes foregrounded (user launches app), the block clears, the container becomes available and the store loads.  Is this not the case for you?

**Comment by lhunath** [comment]
Interestingly, I couldn't get the app to load the store anymore from a background launch, until I quit it and started the app once manually, then quit it again and started it as a background fetch again.  Now the app always fully loads the ubiquity store in the background.

It seems you can't really rely on when or whether the ubiquity store will be available when you're in the background.  Since we're blocking on Apple API and there's no other application threads that could be causing the blocks, I think our hands are pretty much tied here.  If you can reproduce the above but are unhappy with the reliability issues it implies, I recommend you file a bug or DTS and hash this out with the Apple Core Data developers.  Alternatively, see if any of them have an opinion on the developer forums.

**Comment by kdbdallas** [comment]
I understand that it wouldn't pull data from iCloud that fast, but shouldn't it be able to load data from the fall back store immediately?

I am not seeing hangs anymore (I will try your steps above) I am just never getting the ability to do any work because I never have a MOC.
I would think I would have access to the fall back store data (local data) that I can access immediately and do my calls against that, and according to Apple my changes to that, should then upload to iCloud as soon as its able to make the connection with iCloud.

(having access to the local data (aka fallback store) immediately is what my other open bug is about as well, so it seems like this might be related)

**Comment by lhunath** [comment]
For the other bug, I need more information (logs would be good).

As for this issue, USM is marginally slower than using the iCloud API directly for loading a store because USM needs to look at the StoreUUID+ file.  This file exists in the iCloud container, and therefore, the iCloud container needs to be available before USM can do its thing.  The reason USM uses a StoreUUID+ file is because it scopes cloud stores using a UUID which allows it to perform the various tasks that you can't do with just iCloud such as migration, corruption recovery, etc.  The UUID concept lays at the very core of what made USM reliable on iOS 6.

As a result, yes, for USM the cloud container needs to be created before USM becomes available which in this case blocks the app on first background launch.  Additionally, this requirement forces USM to load the store asynchronously which means it's not instantly (synchronously) available.

After the cloud container has been created, USM with the cloud store active will use Apple's fallback store whenever the device is offline or not yet in sync.

**Comment by lhunath** [comment]
So again, I think your options are:
- block `performFetch` until the MOC comes up, even if it's with a timeout of 2 seconds (if timeout, just give up).
- do nothing in `performFetch` if the MOC is not yet up, wait for the next event.

**Comment by kdbdallas** [comment]
This does seem to be working now. Thanks

**Comment by henneonrails** [comment]
hi @kdbdallas 

could you post me an example or snippet of code that is fired in the 

```
- (void)application:(UIApplication *)application performFetchWithCompletionHandler:(void (^) UIBackgroundFetchResult result))completionHandler
```

i can't imagine how to merge data here. Thank you.

**Comment by kdbdallas** [comment]
You don't merge data there.
You do a background fetch, save data to Core Data if appropriate, and exit passing the completion block if you got new data or not

**Comment by henneonrails** [comment]
OK I understand, thank you.

On Fri, Jan 3, 2014 at 6:04 PM, Dallas Brown notifications@github.comwrote:

> You don't merge data there.
> You do a background fetch, save data to Core Data if appropriate, and exit
> passing the completion block if you got new data or not
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lhunath/UbiquityStoreManager/issues/20#issuecomment-31536391
> .

## 

Holger Hänisch | Friedrich-Ebert-Str. 15 | 41539 Dormagen
02133 10605 | 0160 5579559
{ holger.haenisch@gmail.com }
