### ISSUE TITLE
enabling iCloud (entering user/password in Setting) not detect while App in background

### ISSUE THREAD

**Issue by udibr** [lhunath/UbiquityStoreManager#30]
logout from iCloud (from Apple's Settings->iCloud->Delete Account)
start UbiquityStoreManagerExample, the iCloud switch is disabled
switch back to Apple's Settings App and login to iCloud
switch back to UbiquityStoreManagerExample and the iCloud switch continue to be disabled

**Comment by lhunath** [comment]
This is by design.

Contrary to how Apple handles iCloud, USM's principle is that there is a distinct difference between a user's iCloud data and a user's local data.  Also contrary is the fact that in USM, each device of the user needs to opt-into using the data from iCloud using `setCloudEnabled`.

This puts the user in control over which apps he wants to use with iCloud and which he doesn't.

When a user signs out of iCloud, USM turns `cloudEnabled` off because obviously, the cloud is no longer available.

When a user signs into iCloud and `cloudEnabled` is on, USM switches to the new user's iCloud store.  If `cloudEnabled` is off, USM does nothing.  Why not?  Well, because `cloudEnabled = NO` means that the user doesn't want to use the iCloud data on this device.  He wants to use his local data.  And just switching stores automatically would be insanely confusing and surprising for him.

If you want the behaviour of always having iCloud enabled when it's available, you can do so by handling `NSUbiquityIdentityDidChangeNotification` or checking `[[NSFileManager defaultManager] ubiquityIdentityToken]` in `applicationDidBecomeActive`.  When you get a non-`nil` ubiquity token, tell your manager to enable iCloud.  Either through `manager.cloudEnabled` (forced switch to iCloud) or `[manager setCloudEnabledAndOverwriteCloudWithLocalIfConfirmed:]` (optional switch with option for user to migrate his current local data).
